"""Health check endpoints."""
from datetime import datetime
from fastapi import APIRouter
from app.config import settings

router = APIRouter()

@router.get("/health")
async def health():
    return {"status": "ok", "version": settings.APP_VERSION, "timestamp": datetime.utcnow().isoformat()}

@router.get("/ready")
async def ready():
    if not settings.OPENAI_API_KEY:
        from fastapi import HTTPException
        raise HTTPException(status_code=503, detail="OPENAI_API_KEY not set")
    return {"status": "ready"}

@router.get("/graph")
async def graph_info():
    return {
        "nodes": {
            "clarifier": "Extracts context, asks one clarifying question if needed",
            "supervisor": "Routes to specialist agents based on query",
            "transport": "Flights, trains, local transit, airport transfers",
            "accommodation": "Hotels, hostels, Airbnb, neighbourhood guide",
            "weather": "Forecasts, seasonal patterns, packing advice",
            "activities": "Attractions, restaurants, local experiences",
            "advisory": "Safety, visa, vaccines, local laws",
            "rescue": "Emergency contacts, hospitals, disruption handling",
            "synthesiser": "Merges agent data and generates day-by-day itinerary",
        },
        "note": "Itinerary is generated by the synthesiser using data from all agents"
    }
